### ISSUE TITLE
"container" class name conflicts with CSS frameworks

### ISSUE THREAD

**Issue by foundryspatial-duncan** [metawin-m/vue-scroll-sync#1]
The template for this component uses a pretty general class name, `container`. This conflicts with CSS frameworks like Vuetify, Bulma, probably Bootstrap and others. It would be great to change this to something like `scroll-sync-container` to prevent these conflicts.

**Comment by metawin-m** [comment]
Thank you for your suggestion. I have change the container class name to be more specific now in version 1.0.5.
